### ISSUE TITLE
There are no instructions to execute the sample

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-aspnet-owin-mvc-samples#12]
In project 01-login, file README.md missing instructions that indicate how to run the project.

1- The description of the example is missing and what it allows.
2- Missing the Requirements section
3- Missing the steps to run this project

This should contain the following sections:

Login
This example shows how to add *** Login / SignUp *** to your application using the hosted version of the `Lock` widget.

You can read a quickstart for this sample here (https://auth0.com/docs/quickstart/webapp/aspnet-core/01-login).

Requirements
*. NET Core 2.0 SDK (https://www.microsoft.com/net/download/core)

To run this project
1. Ensure that you have replaced the appsettings.json (SampleMvcApp / appsettings.json) file with the values for your Auth0 account.

2. Run the application from the command line:

     `` `bash
     dotnet run
     `` `

3. Go to `http: // localhost: 5000` in your web browser to view the website.

![image](https://user-images.githubusercontent.com/15782359/34360633-f431d3fe-ea38-11e7-9260-e42952908d22.png)

**Comment by jerriep** [comment]
@rafanog I think you have things mixed up. This is the OWIN repo, but your instructions refer to ASP.NET Core which is not relevant for this sample. Also, this sample **does** contain instructions already?

**Comment by jerriep** [comment]
Closing due to lack of response.
