### ISSUE TITLE
client.GetTokenAsync returns exception

### ISSUE THREAD

**Issue by stsomewheredesign** [auth0-samples/auth0-aspnet-owin-mvc-samples#13]
I'm following this sample and receiving an error in the AccountController when executing `client.GetTokenAsync()`. An error of `"Cannot read property 'type' of undefined"` which appears to be thrown by the `Auth0.Core` dll.

The StackTrace is:

   at Auth0.Core.Http.ApiConnection.<HandleErrors>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Auth0.Core.Http.ApiConnection.<RunAsync>d__19`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Auth0.Core.Http.ApiConnection.<PostAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Auth0Owin.Controllers.AccountController.<Login>d__3.MoveNext() in C:\Source\Auth0Owin\Auth0Owin\Controllers\AccountController.cs:line 46

Any assistance would be appreciated.

**Comment by stsomewheredesign** [comment]
Jerri,

I was poking around with this a bit more this morning, and found the `ResourceOwnerTokenRequest` class has a property called `Audience`. From what I can tell, this may be what's causing the issue above. When I pass in something, ie. `http://localhost:61122` I receive an error now saying `invalid audience specified for password grant exchange`.

It still looks to be occurring in the `Auth0.Core.dll`.

I checked the code for the attached QuickStart and noticed it does not have an `Audience` property assigned, and fails at the same place with the same error(s) depending on whether `Audience` is left out, or if the URL for my localhost instance is set.

**Comment by jerriep** [comment]
@stsomewheredesign I assume you are referring to the `/Samples/custom-login` sample, is that correct?

I think it could be because your Client is not configured as OIDC Conformant. See https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant

Can you please check and let me know?

**Comment by stsomewheredesign** [comment]
@jerriep Yes, I've been working with the `/Samples/custom-login` sample, and I have tried the sample with the OIDC Conformant flag both set and unset.

I tried again this morning with the OIDC Conformant flag set, and when not providing an `Audience` I continue to receive the `cannot read property 'type' of undefined`. When providing my Client domain as the value for `Audience`, I receive the error `invalid audience specified for password grant exchange`.

Of course, it's entirely possible I'm using the wrong value for `Audience` as hinted in the error, so I've tried `fnf-int.auth0.com`, `http://fnf-int.auth0.com` and `https://fnf-int.auth0.com`. I've even tried `http://fnf-int.auth0.com/oauth/token` and `https://fnf-int.auth0.com/oauth/token`.

I'm not sure what to try next. It's a bit frustrating that the pure sample is exhibiting the same behavior that my butchered attempt is exhibiting which makes me think that either I'm pushing incorrect value(s) somewhere, or there truly is an error in `Auth0.Core`. Of course, my hands have been further tied by management decisions to not move to the new Lock, they "have to" have the custom login screen, so it's imperative I get this working.

Thanks much for the help!

**Comment by jerriep** [comment]
It should work without Audience. The Audience should be a value API Identifier, so you will need to create an API with that Identifier in the APIs section of the Auth0 Dashboard.

Can you please send me the exact snippet of code you use to configure the middleware. If you use configuration values (i.e. read it from web.config), then send me the actual values as well. Also, send me a username / password combination I can use to test with.

This info I am requestion contains sensitive information (e.g. client secrets), so don't post it here. Send it to me at jerrie@jerriepelser.com

It is evening over here, but I can look at it for you in the morning

**Comment by jerriep** [comment]
BTW, can you tried to use execute the Resource Owner Password flow using the Postman collections?

You can download the Postman collections over here:
https://auth0.com/docs/api/postman

You should use this one:
![2018-01-10_21-21-55](https://user-images.githubusercontent.com/1006420/34777262-5725f408-f64c-11e7-949e-7920b5e5ff6e.png)

**Comment by stsomewheredesign** [comment]
@jerriep Email with the project I'm using is headed your way now (10Mb) and I'll take a look at the Postman collection your referenced above.

Thanks again for the help!

**Comment by jerriep** [comment]
Closing this as issue was related to a faulty Rule
