### ISSUE TITLE
ASP.NET (OWIN) Regular Web App: Signature validation error when login in or signing up

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-aspnet-owin-mvc-samples#15]
**Enviroment Information**
- Visual Studio 2017 v15.7.6
- Google Chrome v68

**Issue**
In the [ASP.NET (OWIN) Quickstart](https://auth0.com/docs/quickstart/webapp/aspnet-owin), when the user tries to log in with a valid account or sign up with a new one, a signature validation error shows up and the user is not able to finish the login process.

**Screenshot**
![login-error](https://user-images.githubusercontent.com/5594487/43848390-d3b766a6-9b00-11e8-83aa-605d7e5a140e.PNG)

**Comment by jerriep** [comment]
A couple of things:

1. Can you show me the code of how you registered the authentication middleware?
2. What is the JsonWebToken Signature Algorithm for this client set as? (Go to your client then Show Advanced Settings > OAuth)

**Comment by mikearias3** [comment]
1. We're using the authentication middleware provided in the sample. The easiest way to enable authentication with Auth0 in your ASP.NET MVC application is to use the OWIN OpenID Connect middleware which is available in the Microsoft.Owin.Security.OpenIdConnect NuGet package. 
![startup-cs-1](https://user-images.githubusercontent.com/5594487/43901145-ba87b05a-9bb4-11e8-8e57-808589f85fe7.PNG)
![startup-cs-2](https://user-images.githubusercontent.com/5594487/43901146-ba9ee9c8-9bb4-11e8-9543-0c1a0824642f.PNG)

2. Here's the JsonWebToken Signature Algorithm.
![jsonwebtokensignature](https://user-images.githubusercontent.com/5594487/43901181-d17058e4-9bb4-11e8-94bd-0ae9bae6bbc6.PNG)

**Comment by jerriep** [comment]
@mikearias3 You should set your JsonWebToken Signature Algorithm to **RS256**, then everything should work fine.

Before you do that though, ensure that no other applications are using that Auth0 application. Or if there are other applications using that Auth0 application, ensure that they now expect RS256-signed tokens.

**Comment by mikearias3** [comment]
Gotcha. That fixed it, thanks!
