### ISSUE TITLE
Error with default configuration

### ISSUE THREAD

**Issue by klpatil** [auth0-samples/auth0-aspnet-owin-mvc-samples#38]
Hello,
I created a new application and followed the required steps as per "I want to explore a sample app". But when I run it getting following error:
"OpenIdConnectMessage.Error was not null, indicating an error. Error: 'access_denied'. Error_Description (may be empty): 'Service not found: YOUR_API_IDENTIFIER'. Error_Uri (may be empty): 'error_uri is null'."

Also, tried hosting in Local IIS with HTTPS. But still no luck.

**Comment by frederikprijck** [comment]
Did you fill out all required properties in the web.config (https://github.com/auth0-samples/auth0-aspnet-owin-mvc-samples/blob/master/Quickstart/01-Login/MvcApplication/MvcApplication/Web.config#L15)?

If you have downloaded the example as part of the quickstart, please note that all these settings are pre-filled if you are logged in. If not, you need tp manually edit them.
