### ISSUE TITLE
Running the application

### ISSUE THREAD

**Issue by hamish-tushar** [auth0-samples/auth0-aspnet-owin-mvc-samples#4]
I am trying to run the application. I have created a new client on auth0 dashboard and added the callback URl http://localhost:56572/signin-auth0 to the client.
When I try to login with my username password for auth0 i get error saying something went wrong? 
What credentials do i need to enter to login?

**Comment by jerriep** [comment]
1. Have you actually registered a user in Auth0 and are you trying to log in with that existing user?
2. Have you set the values for your Auth0 settings (domain, client id, etc) in the web.config
3. Look in the Auth0 Dashboard under the Logs to see if you can see more information about what the exact error is.
4. Have a look at the network tab in your browser. See if you can see any more details about what the exact error is

**Comment by jerriep** [comment]
@hamish-tushar I am closing this issue, as I have not heard anything back from you.

If you wish to pursue this further please open an issue with Auth0 support:
https://support.auth0.com/
