### ISSUE TITLE
missing instruction in readme.md

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-aspnet-owin-mvc-samples#6]
(AUTH-3988)
Readme.md of samples that implements logout should inform user that he should register `http://localhost:56572/` as a `Allowed Logout URLs`. 
![image](https://cloud.githubusercontent.com/assets/1114365/26006978/3feab716-3747-11e7-92ce-de83de737137.png)

**Comment by jerriep** [comment]
Closed with 9a9d6d644f9ca4063dca0df1e53f8efd2042f237
