### ISSUE TITLE
Set up the Kentor.OwinCookieSaver package in the samples and seeds

### ISSUE THREAD

**Issue by nicosabena** [auth0-samples/auth0-aspnet-owin-mvc-samples#8]
As explained in https://github.com/auth0/auth0-aspnet-owin#katana-issue-with-cookies, the OWIN middleware sometimes fails to set the session cookie (or rather, it losses it). The aforementioned package fixes the problem, we should put it in the samples and seeds.

The quickstart doc should be updated as well to include a mention to it.

**Comment by jerriep** [comment]
@nicosabena I will get to it hopefully sometime later in this week or next week
